import { CEFRLevel } from "@/generated/prisma/enums";
import { LevelCurriculum } from "../types";

export const a1Curriculum: LevelCurriculum = {
  level: CEFRLevel.A1,
  label: "Beginner",
  description: "Can understand and use familiar everyday expressions and basic phrases.",
  languageBalance: "Predominantly English with generous French woven in. Introduce new vocabulary in context with immediate English support. Encourage but never pressure French production.",
  vocabularyClusters: [
    {
      name: "Self & identity",
      conceptId: "vocab.self_identity",
      words: ["je m'appelle", "j'ai X ans", "je suis", "j'habite à", "je viens de"],
    },
    {
      name: "Family",
      conceptId: "vocab.family",
      words: ["mère", "père", "frère", "sœur", "fils", "fille", "mari", "femme", "enfant", "famille", "grand-père", "grand-mère"],
    },
    {
      name: "Numbers",
      conceptId: "vocab.numbers_1_100",
      words: ["onze", "vingt", "trente", "quarante", "cinquante", "soixante", "soixante-dix", "quatre-vingts", "quatre-vingt-dix", "cent", "premier", "deuxième"],
    },
    {
      name: "Time",
      conceptId: "vocab.time_days_months",
      words: ["heure", "minute", "lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche", "janvier", "février", "mars", "aujourd'hui", "demain", "hier"],
    },
    {
      name: "Food & drink",
      conceptId: "vocab.food_drink",
      words: ["petit-déjeuner", "déjeuner", "dîner", "poulet", "riz", "salade", "fruit", "lait", "jus", "bière", "vin", "fromage", "pain", "beurre"],
    },
    {
      name: "Colors",
      conceptId: "vocab.colors",
      words: ["rouge", "bleu", "vert", "blanc", "noir", "jaune", "gris", "rose", "orange", "marron"],
    },
    {
      name: "Common objects",
      conceptId: "vocab.common_objects",
      words: ["livre", "stylo", "table", "chaise", "téléphone", "ordinateur", "porte", "fenêtre", "clé", "sac"],
    },
    {
      name: "Weather",
      conceptId: "vocab.weather",
      words: ["il fait chaud", "il fait froid", "il fait beau", "il pleut", "il neige", "le soleil", "le vent", "le nuage"],
    },
    {
      name: "Places",
      conceptId: "vocab.places",
      words: ["ville", "rue", "magasin", "restaurant", "gare", "aéroport", "hôpital", "hôtel", "école", "bureau"],
    },
    {
      name: "Emotions",
      conceptId: "vocab.emotions_basic",
      words: ["content", "triste", "fatigué", "heureux", "en colère", "j'ai peur", "surpris"],
    },
    {
      name: "Common verbs",
      conceptId: "vocab.common_verbs",
      words: ["manger", "boire", "dormir", "travailler", "parler", "écouter", "regarder", "aimer", "vouloir", "pouvoir", "lire", "écrire"],
    },
  ],
  grammarConcepts: [
    {
      conceptId: "grammar.subject_pronouns",
      name: "Subject pronouns",
      description: "je, tu, il/elle/on, nous, vous, ils/elles",
      examples: ["Je suis étudiant.", "Elle est française.", "Nous sommes amis."],
    },
    {
      conceptId: "grammar.etre_present",
      name: "Être — present tense",
      description: "Full conjugation of être in the present",
      examples: ["Je suis content.", "Tu es fatigué.", "Il est grand.", "Nous sommes ici."],
    },
    {
      conceptId: "grammar.avoir_present",
      name: "Avoir — present tense",
      description: "Full conjugation of avoir in the present",
      examples: ["J'ai 20 ans.", "Tu as un frère.", "Elle a faim.", "Nous avons le temps."],
    },
    {
      conceptId: "grammar.articles",
      name: "Articles",
      description: "Definite (le, la, les) and indefinite (un, une, des) articles with gender",
      examples: ["Le livre est sur la table.", "Un homme et une femme.", "Des enfants jouent."],
    },
    {
      conceptId: "grammar.er_verbs_present",
      name: "Regular -er verbs present tense",
      description: "Conjugation pattern for regular -er verbs",
      examples: ["Je parle français.", "Tu manges du pain.", "Il travaille ici.", "Nous aimons le cinéma."],
    },
    {
      conceptId: "grammar.negation_basic",
      name: "Basic negation",
      description: "ne...pas structure",
      examples: ["Je ne suis pas français.", "Il ne mange pas.", "Nous n'aimons pas le froid."],
    },
    {
      conceptId: "grammar.questions_basic",
      name: "Basic question formation",
      description: "Est-ce que + intonation questions",
      examples: ["Est-ce que tu parles français?", "Tu habites où?", "Comment tu t'appelles?"],
    },
    {
      conceptId: "grammar.possessive_adj",
      name: "Possessive adjectives",
      description: "mon/ma/mes, ton/ta/tes, son/sa/ses",
      examples: ["Mon frère est grand.", "Ta mère est gentille.", "Ses amis sont ici."],
    },
    {
      conceptId: "grammar.aller_present",
      name: "Aller — present + futur proche",
      description: "Aller in present tense and aller + infinitive for near future",
      examples: ["Je vais à l'école.", "Tu vas manger.", "Nous allons partir demain."],
    },
    {
      conceptId: "grammar.il_y_a",
      name: "Il y a",
      description: "Expressing 'there is / there are'",
      examples: ["Il y a un chat.", "Il y a des livres sur la table.", "Il n'y a pas de problème."],
    },
    {
      conceptId: "grammar.cest_vs_ilest",
      name: "C'est vs Il/Elle est",
      description: "When to use c'est vs il/elle est",
      examples: ["C'est un bon livre.", "Il est français.", "C'est mon ami."],
    },
    {
      conceptId: "grammar.faire_present",
      name: "Faire — present tense",
      description: "Conjugation and common expressions with faire",
      examples: ["Il fait beau.", "Je fais du sport.", "Qu'est-ce que tu fais?"],
    },
    {
      conceptId: "grammar.vouloir_pouvoir",
      name: "Vouloir & Pouvoir — present",
      description: "Expressing wants and abilities, including je voudrais for politeness",
      examples: ["Je veux un café.", "Je voudrais un croissant.", "Tu peux m'aider?"],
    },
  ],
  listeningTasks: [
    "Understand short French sentences with context clues",
    "Respond to simple French questions",
    "Identify key words in tutor's French sentences",
  ],
  readingTasks: [
    "2-3 sentence passages from the tutor",
    "Simple descriptions and short dialogues",
  ],
  speakingTasks: [
    "Answer questions in French with short phrases",
    "Self-introduction in French",
    "Order food at a restaurant",
    "Describe family members",
    "Express likes and dislikes",
  ],
  writingTasks: [
    "Construct simple SVO sentences",
    "Answer questions in writing",
    "Fill in responses to tutor prompts",
  ],
  masteryEvidence: [
    "Can introduce themselves fluently in French",
    "Conjugates être, avoir, aller, and 5+ -er verbs correctly >70%",
    "Forms negation and questions correctly >60%",
    "Uses correct articles >50% of the time",
    "Actively produces 80+ vocabulary words across target clusters",
    "Demonstrated across 5+ sessions with interleaved topics",
  ],
  conceptIds: [
    "grammar.subject_pronouns",
    "grammar.etre_present",
    "grammar.avoir_present",
    "grammar.articles",
    "grammar.er_verbs_present",
    "grammar.negation_basic",
    "grammar.questions_basic",
    "grammar.possessive_adj",
    "grammar.aller_present",
    "grammar.il_y_a",
    "grammar.cest_vs_ilest",
    "grammar.faire_present",
    "grammar.vouloir_pouvoir",
    "vocab.self_identity",
    "vocab.family",
    "vocab.numbers_1_100",
    "vocab.time_days_months",
    "vocab.food_drink",
    "vocab.colors",
    "vocab.common_objects",
    "vocab.weather",
    "vocab.places",
    "vocab.emotions_basic",
    "vocab.common_verbs",
  ],
};
