import { CEFRLevel } from "@/generated/prisma/enums";
import { LevelCurriculum } from "../types";

export const a2Curriculum: LevelCurriculum = {
  level: CEFRLevel.A2,
  label: "Elementary",
  description: "Can understand sentences relating to areas of most immediate relevance. Can communicate in simple, routine tasks.",
  languageBalance: "English reducing significantly. Simple French conversations with English support when needed. Encourage full French sentences.",
  vocabularyClusters: [
    {
      name: "Daily routines (reflexive)",
      conceptId: "vocab.daily_routines",
      words: ["se réveiller", "se lever", "se doucher", "s'habiller", "se coucher", "se brosser les dents", "se maquiller", "se préparer"],
    },
    {
      name: "Health & body",
      conceptId: "vocab.health_body",
      words: ["tête", "bras", "jambe", "dos", "ventre", "malade", "médicament", "médecin", "j'ai mal à", "fièvre", "rhume", "pharmacie"],
    },
    {
      name: "Shopping",
      conceptId: "vocab.shopping",
      words: ["combien", "cher", "bon marché", "taille", "acheter", "vendre", "payer", "l'argent", "carte", "caisse", "soldes", "prix"],
    },
    {
      name: "Transportation",
      conceptId: "vocab.transportation",
      words: ["voiture", "bus", "train", "avion", "vélo", "métro", "conduire", "arrêt", "billet", "gare", "station", "horaire"],
    },
    {
      name: "House & rooms",
      conceptId: "vocab.house_rooms",
      words: ["cuisine", "salon", "chambre", "salle de bain", "jardin", "étage", "meubles", "lit", "canapé", "frigo", "escalier"],
    },
    {
      name: "Hobbies",
      conceptId: "vocab.hobbies",
      words: ["sport", "musique", "cinéma", "lecture", "voyage", "jouer", "nager", "courir", "dessiner", "cuisiner", "danser"],
    },
    {
      name: "Work & study",
      conceptId: "vocab.work_study",
      words: ["travail", "bureau", "cours", "examen", "professeur", "étudiant", "réunion", "devoirs", "notes", "emploi du temps"],
    },
    {
      name: "Directions",
      conceptId: "vocab.directions",
      words: ["à gauche", "à droite", "tout droit", "en face de", "à côté de", "entre", "devant", "derrière", "près de", "loin de"],
    },
    {
      name: "Comparisons",
      conceptId: "vocab.comparisons",
      words: ["plus", "moins", "aussi", "mieux", "meilleur", "pire", "autant", "tellement"],
    },
  ],
  grammarConcepts: [
    {
      conceptId: "grammar.passe_compose_avoir",
      name: "Passé composé with avoir",
      description: "Past tense with avoir auxiliary for regular verbs",
      examples: ["J'ai mangé du fromage.", "Elle a regardé le film.", "Nous avons parlé longtemps."],
    },
    {
      conceptId: "grammar.passe_compose_etre",
      name: "Passé composé with être",
      description: "Past tense with être auxiliary — DR MRS VANDERTRAMP verbs",
      examples: ["Je suis allé au cinéma.", "Elle est partie hier.", "Ils sont arrivés en retard."],
    },
    {
      conceptId: "grammar.passe_compose_agreement",
      name: "Passé composé agreement",
      description: "Agreement rules with être auxiliary",
      examples: ["Elle est allée à Paris.", "Elles sont parties tôt.", "Nous sommes arrivés ensemble."],
    },
    {
      conceptId: "grammar.imparfait",
      name: "Imparfait",
      description: "Formation and usage for descriptions and habitual past actions",
      examples: ["Quand j'étais petit, j'aimais le chocolat.", "Il faisait beau ce jour-là.", "Nous habitions à Lyon."],
    },
    {
      conceptId: "grammar.pc_vs_imparfait",
      name: "Passé composé vs imparfait",
      description: "Choosing between PC (completed actions) and imparfait (background/habitual)",
      examples: ["Je dormais quand le téléphone a sonné.", "Il pleuvait et j'ai pris un taxi."],
    },
    {
      conceptId: "grammar.reflexive_present",
      name: "Reflexive verbs — present",
      description: "Present tense conjugation of reflexive verbs",
      examples: ["Je me lève à 7 heures.", "Tu te couches tard.", "Elle se prépare vite."],
    },
    {
      conceptId: "grammar.direct_indirect_pronouns",
      name: "Direct & indirect object pronouns",
      description: "le, la, les (direct) and lui, leur (indirect)",
      examples: ["Je le vois.", "Je lui parle.", "Tu les connais?"],
    },
    {
      conceptId: "grammar.comparatif_superlatif",
      name: "Comparative & superlative",
      description: "plus...que, moins...que, le plus, le moins",
      examples: ["Paris est plus grand que Lyon.", "C'est le meilleur restaurant.", "Elle court moins vite que moi."],
    },
    {
      conceptId: "grammar.prepositions_place",
      name: "Prepositions of place",
      description: "à, en, au, aux with countries and cities",
      examples: ["J'habite à Paris.", "Je vais en France.", "Il est au Japon.", "Elles sont aux États-Unis."],
    },
    {
      conceptId: "grammar.y_en_intro",
      name: "Y and en (introduction)",
      description: "Replacing places with y and quantities with en",
      examples: ["Tu vas à Paris? Oui, j'y vais.", "Tu as des amis? Oui, j'en ai beaucoup."],
    },
    {
      conceptId: "grammar.futur_simple_intro",
      name: "Futur simple (introduction)",
      description: "Basic future tense forms of common verbs",
      examples: ["Je serai là demain.", "Tu auras le temps.", "Nous irons ensemble."],
    },
    {
      conceptId: "grammar.imperative",
      name: "Imperative mood",
      description: "Giving commands and suggestions",
      examples: ["Mange ta soupe!", "Allons-y!", "Écoutez bien!"],
    },
    {
      conceptId: "grammar.partitif",
      name: "Partitive articles",
      description: "du, de la, des, de l' for unspecified quantities",
      examples: ["Je veux du pain.", "Tu bois de l'eau.", "Il n'y a pas de lait."],
    },
  ],
  listeningTasks: [
    "Follow tutor paragraphs in French with occasional English",
    "Understand short stories told by the tutor",
    "Answer comprehension questions about spoken narratives",
  ],
  readingTasks: [
    "Paragraphs of 5-10 sentences",
    "Short narratives about daily life",
    "Simple email or letter format",
  ],
  speakingTasks: [
    "Describe past events in detail",
    "Give and follow directions",
    "Compare people, places, or things",
    "Express opinions and preferences with reasons",
    "Narrate daily routines using reflexive verbs",
    "Discuss future plans",
  ],
  writingTasks: [
    "Write short paragraphs of 3-5 sentences",
    "Describe a scene or picture",
    "Write about past weekend activities",
    "Express preferences with supporting reasons",
  ],
  masteryEvidence: [
    "Uses passé composé and imparfait with >65% accuracy",
    "Shows understanding of PC vs imparfait distinction",
    "Can narrate past events coherently",
    "Uses reflexive verbs in daily routine descriptions",
    "Produces paragraphs with connected sentences",
    "Vocabulary: 300+ active words across target clusters",
    "Can sustain 10-exchange French conversation with minimal English",
    "Demonstrated across 8+ sessions",
  ],
  conceptIds: [
    "grammar.passe_compose_avoir",
    "grammar.passe_compose_etre",
    "grammar.passe_compose_agreement",
    "grammar.imparfait",
    "grammar.pc_vs_imparfait",
    "grammar.reflexive_present",
    "grammar.direct_indirect_pronouns",
    "grammar.comparatif_superlatif",
    "grammar.prepositions_place",
    "grammar.y_en_intro",
    "grammar.futur_simple_intro",
    "grammar.imperative",
    "grammar.partitif",
    "vocab.daily_routines",
    "vocab.health_body",
    "vocab.shopping",
    "vocab.transportation",
    "vocab.house_rooms",
    "vocab.hobbies",
    "vocab.work_study",
    "vocab.directions",
    "vocab.comparisons",
  ],
};
