import { CEFRLevel } from "@/generated/prisma/enums";
import { LevelCurriculum } from "../types";

export const b1Curriculum: LevelCurriculum = {
  level: CEFRLevel.B1,
  label: "Intermediate",
  description: "Can deal with most situations likely to arise while travelling. Can produce simple connected text on familiar topics.",
  languageBalance: "Mostly French. English only when the learner is genuinely lost or for complex explanations they explicitly request. Default to French for everything.",
  vocabularyClusters: [
    {
      name: "Emotions & opinions (nuanced)",
      conceptId: "vocab.emotions_nuanced",
      words: ["déçu", "soulagé", "inquiet", "fier", "impressionné", "il me semble que", "à mon avis", "je trouve que", "je crois que", "ému", "enthousiaste"],
    },
    {
      name: "News & current events",
      conceptId: "vocab.news_events",
      words: ["actualité", "gouvernement", "élection", "économie", "environnement", "société", "politique", "manifestation", "sondage", "loi"],
    },
    {
      name: "Work life (advanced)",
      conceptId: "vocab.work_advanced",
      words: ["CV", "entretien", "salaire", "collègue", "projet", "délai", "compétence", "candidature", "embaucher", "licencier"],
    },
    {
      name: "Education",
      conceptId: "vocab.education",
      words: ["matière", "diplôme", "licence", "master", "recherche", "mémoire", "stage", "bourse", "formation", "soutenance"],
    },
    {
      name: "Abstract concepts",
      conceptId: "vocab.abstract_concepts",
      words: ["liberté", "égalité", "justice", "progrès", "responsabilité", "avenir", "réussite", "expérience", "conséquence"],
    },
    {
      name: "Discourse markers",
      conceptId: "vocab.discourse_markers",
      words: ["cependant", "néanmoins", "en revanche", "par conséquent", "d'ailleurs", "malgré", "bien que", "afin de", "pourtant", "donc"],
    },
  ],
  grammarConcepts: [
    {
      conceptId: "grammar.subjonctif_present",
      name: "Subjonctif présent",
      description: "Formation and key triggers: il faut que, je veux que, bien que, pour que, avant que",
      examples: ["Il faut que je fasse mes devoirs.", "Je veux que tu viennes.", "Bien qu'il soit tard, je travaille."],
    },
    {
      conceptId: "grammar.conditionnel_present",
      name: "Conditionnel présent",
      description: "Formation and usage for politeness, hypotheticals, wishes",
      examples: ["Je voudrais un café.", "Si j'avais le temps, je voyagerais.", "Tu pourrais m'aider?"],
    },
    {
      conceptId: "grammar.si_clauses_1_2",
      name: "Si clauses (types 1 & 2)",
      description: "si + présent → futur; si + imparfait → conditionnel",
      examples: ["Si tu viens, je serai content.", "Si j'étais riche, j'achèterais une maison."],
    },
    {
      conceptId: "grammar.plus_que_parfait",
      name: "Plus-que-parfait",
      description: "Formation and usage for events before other past events",
      examples: ["J'avais déjà mangé quand il est arrivé.", "Elle avait fini avant moi."],
    },
    {
      conceptId: "grammar.relative_pronouns",
      name: "Relative pronouns",
      description: "qui, que, où, dont for building complex sentences",
      examples: ["Le livre que j'ai lu est intéressant.", "La ville où j'habite est belle.", "L'ami dont je t'ai parlé."],
    },
    {
      conceptId: "grammar.pronoun_placement_compound",
      name: "Pronoun placement in compound tenses",
      description: "Position of pronouns with passé composé and other compound forms",
      examples: ["Je l'ai vu hier.", "Elle s'est levée tôt.", "Nous les avons invités."],
    },
    {
      conceptId: "grammar.passive_intro",
      name: "Passive voice (introduction)",
      description: "Basic passive constructions",
      examples: ["La maison a été construite en 1900.", "Le livre est lu par beaucoup de gens."],
    },
    {
      conceptId: "grammar.gerondif",
      name: "Gérondif (present participle)",
      description: "en + present participle for simultaneous actions",
      examples: ["En marchant, j'écoute de la musique.", "Il a appris en pratiquant."],
    },
    {
      conceptId: "grammar.y_en_mastery",
      name: "Y and en (mastery)",
      description: "Advanced usage of y and en in various contexts",
      examples: ["J'y pense souvent.", "Il en a besoin.", "N'y va pas!"],
    },
    {
      conceptId: "grammar.double_pronouns",
      name: "Double pronoun order",
      description: "Using two pronouns together in correct order",
      examples: ["Je le lui ai donné.", "Elle me l'a dit.", "Donne-le-moi!"],
    },
  ],
  listeningTasks: [
    "Follow complex narratives with embedded clauses",
    "Discuss hypothetical scenarios in French",
    "Understand implicit meaning in tutor's responses",
  ],
  readingTasks: [
    "Full paragraphs with complex sentence structure",
    "News-style passages about current events",
    "Opinion texts and editorials",
    "Short fiction excerpts",
  ],
  speakingTasks: [
    "Defend opinions with reasons and examples",
    "Narrate complex past events with multiple tenses",
    "Discuss hypothetical situations",
    "Explain causes and consequences",
    "Summarize articles or stories",
  ],
  writingTasks: [
    "Structured paragraphs with introduction, body, conclusion",
    "Express and defend an opinion in writing",
    "Narrate a complex event in multiple tenses",
    "Write in both formal and informal register",
  ],
  masteryEvidence: [
    "Uses subjunctive correctly in common triggers >60%",
    "Produces conditional + si clauses accurately",
    "Can defend an opinion with reasons and examples in French",
    "Uses relative pronouns to build complex sentences",
    "Shows comfort with all past tenses (PC, imparfait, PQP) in sustained narrative",
    "Sustains full conversation in French with English <5%",
    "500+ active vocabulary including abstract concepts",
    "Demonstrated across 10+ sessions",
  ],
  conceptIds: [
    "grammar.subjonctif_present",
    "grammar.conditionnel_present",
    "grammar.si_clauses_1_2",
    "grammar.plus_que_parfait",
    "grammar.relative_pronouns",
    "grammar.pronoun_placement_compound",
    "grammar.passive_intro",
    "grammar.gerondif",
    "grammar.y_en_mastery",
    "grammar.double_pronouns",
    "vocab.emotions_nuanced",
    "vocab.news_events",
    "vocab.work_advanced",
    "vocab.education",
    "vocab.abstract_concepts",
    "vocab.discourse_markers",
  ],
};
